version: "2.1"
volumes:
  x11:
  shared-data:
  redis-data:
services:
  gui:
    build: ./gui
    restart: always
    privileged: true
    devices:
      - /dev/dri
    group_add:
      - video
    volumes:
      - 'x11:/tmp/.X11-unix'
      - 'shared-data:/data/my_data'
    environment:
      - DISPLAY=:0
    depends_on:
      - xserver
  xserver:
    image: balenablocks/xserver:latest
    restart: always
    privileged: true
    volumes:
      - 'x11:/tmp/.X11-unix'
  redis:
    image: redis:6.2.4-alpine
    command: ["redis-server", "--save", "60", "250"]
    volumes:
      - redis-data:/data
  flowdock:
    restart: always
    privileged: true
    build: ./flowdock
    volumes:
      - 'shared-data:/data/my_data'
    labels:
      io.balena.features.supervisor-api: '1'
