FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.7

RUN install_packages libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libmtdev-dev

RUN pip install kivy

WORKDIR /usr/src/app

COPY hello.py ./

COPY start.sh ./

CMD ["bash","./start.sh"]