FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu-python:3.7-bionic-build

WORKDIR /usr/src/app

RUN pip3 install pillow requests redis flowdock-api-wrapper

COPY *.py ./

COPY start.sh ./

CMD ["bash","./start.sh"]

